# Generated by Django 5.0.4 on 2024-04-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoTicketsApp', '0005_purchase_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
