# Generated by Django 5.0.4 on 2024-05-08 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoTicketsApp', '0008_card'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='card',
            new_name='Cardd',
        ),
    ]
