# Generated by Django 5.0.4 on 2024-07-28 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoTicketsApp', '0012_event_address_event_location_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
    ]
