# Generated by Django 5.0.4 on 2024-07-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoTicketsApp', '0014_event_age_restriction_event_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='price',
            new_name='friday_price',
        ),
        migrations.AddField(
            model_name='event',
            name='sunday_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='event',
            name='seats',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
