# Generated by Django 5.0.4 on 2024-07-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoTicketsApp', '0015_rename_price_event_friday_price_event_sunday_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='friday_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sunday_price',
        ),
    ]
