# Generated by Django 5.0.4 on 2024-07-30 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoTicketsApp', '0021_ticket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
    ]
