# Generated by Django 5.0.4 on 2024-07-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoTicketsApp', '0022_remove_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='full_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
