# Generated by Django 5.0.4 on 2024-08-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoTicketsApp', '0023_card_full_name_alter_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('expired', 'Expired'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=10),
        ),
    ]
